Repository hinasuleman/m44-final-project-fe, pull requests merged in 2023-02, with the labels that each got.

#1 test comment
  src/pages/landingPage/landingPage.js
Labels: enhancement

#3 Feature/landingpage
  src/pages/landingPage/landingPage.js
Labels: enhancement

#5 Feature/navigation
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
Labels: enhancement

#6 Landingpage login sq
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/landingPage/landingPage.js
Labels: enhancement

#7 Feature/landingpage
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/landingPage/landingPage.js
Labels: enhancement

#8 Dev
  package-lock.json
  package.json
  src/App.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/layout/Layout.css
  src/components/layout/Layout.js
  src/components/modals/addbookmodal/AddBookModal.css
  src/components/modals/addbookmodal/AddBookModal.js
  src/components/modals/bookinfomodal/BookInfoModal.css
  src/components/modals/bookinfomodal/BookInfoModal.js
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/components/modals/searchresultmodal/SearchResultModal.css
  src/components/modals/searchresultmodal/SearchResultModal.js
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/index.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/sigupPage.js
  src/pages/userprofilePage/userprofilePage.css
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
Labels: enhancement

#9 logo images
  Logo images.zip
Labels: images

#10 Mainpage fetchapi cs
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/images/blankCover.jpg
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/utilities/utilities.js
Labels: enhancement

#11 Feature/mainpage
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/images/blankCover.jpg
  src/pages/mainPage/mainPage.js
  src/utilities/utilities.js
Labels: enhancement

#12 Signuppage addform hs
  package-lock.json
  package.json
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/blankCover.jpg
  src/index.js
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/sigupPage.js
  src/utilities/utilities.js
Labels: enhancement

#13 Feature/signuppage
  src/App.js
  src/pages/signupPage/sigupPage.js
Labels: enhancement

#18 Feature/userprofilepage
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#17 Landingpage css sq
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
Labels: enhancement

#19 Feature/landingpage
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
Labels: enhancement

#20 Navigation navbarmenu ac
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/index.js
Labels: enhancement

#21 Feature/navigation
  public/index.html
  src/App.css
  src/App.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/index.js
Labels: enhancement

#25 library component updated
  src/components/libraryContainer/LibraryContainer..js
  src/components/libraryContainer/LibraryContainer.js
Labels: bug, enhancement

#26 24 fix file name
  src/pages/mainPage/mainPage.js
  src/pages/userprofilePage/userprofilePage.js
Labels: bug

#23 Dev
  public/index.html
  src/App.css
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/images/blankCover.jpg
  src/index.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/sigupPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/utilities.js
Labels: enhancement

#31 Navigation navbar ac
  public/index.html
  src/App.css
  src/App.js
  src/components/libraryContainer/LibraryContainer..js
  src/components/libraryContainer/LibraryContainer.js
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/components/wishlistContainer/WishlistContainer.js
  src/index.js
  src/pages/landingPage/landingPage.css
  src/pages/mainPage/mainPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.js
Labels: enhancement

#32 Feature/navigation
  public/index.html
  src/App.css
  src/App.js
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
Labels: enhancement

#36 Feature/userprofilepage
  src/App.js
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#38 Feature/signuppage
  src/images/homeBookCase.jpeg
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/sigupPage.js
Labels: enhancement

#41 Feature/landing page css sq
  public/index.html
  src/App.css
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/images/blankCover.jpg
  src/index.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/sigupPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/utilities.js
Labels: enhancement

#45 Mainpage fetchapi cs
  .gitignore
  public/index.html
  src/App.js
  src/components/libraryContainer/LibraryContainer..js
  src/components/libraryContainer/LibraryContainer.js
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.js
Labels: enhancement

#46 Feature/mainpage
  .gitignore
  public/index.html
  src/App.js
  src/components/libraryContainer/LibraryContainer.js
  src/pages/signupPage/signupPage.js
Labels: enhancement

#47 Dev
  .gitignore
  public/index.html
  src/App.css
  src/App.js
  src/components/libraryContainer/LibraryContainer.js
  src/components/navigation/MenuData.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/homeBookCase.jpeg
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/signupPage.js
  src/pages/signupPage/sigupPage.js
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#48 Signuppage styling ac
  .gitignore
  public/index.html
  src/App.js
  src/components/libraryContainer/LibraryContainer.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/signupPage/signupPage.js
  src/pages/signupPage/sigupPage.js
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#49 Feature/signuppage
  src/pages/landingPage/landingPage.js
  src/pages/signupPage/signupPage.js
  src/pages/signupPage/sigupPage.js
Labels: enhancement

#50 Feature/mainpage
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
Labels: enhancement

#52 Feature/userprofilepage
  1.png
  2.png
  3.png
  images/Code Book (1).zip
  src/components/modals/deleteusermodal/DeleteUserModal.js
Labels: enhancement

#53 Mainpage css hm
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.js
  src/pages/signupPage/sigupPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
Labels: enhancement

#57 Navigation navbar ac
  .gitignore
  package-lock.json
  public/index.html
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/homeBookCase.jpeg
  src/images/icons/book.png
  src/images/icons/heart.png
  src/images/icons/people-arrows.png
  src/images/icons/people-group.png
  src/images/icons/user.png
  src/images/logo/logo_1.png
  src/images/logo/logo_2.png
  src/images/logo/logo_3.png
  src/images/logo/logo_outline.png
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/signupPage.js
  src/pages/signupPage/sigupPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
Labels: enhancement

#58 Feature/navigation
  1.png
  2.png
  3.png
  images/Code Book (1).zip
  package-lock.json
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/icons/book.png
  src/images/icons/heart.png
  src/images/icons/people-arrows.png
  src/images/icons/people-group.png
  src/images/icons/user.png
  src/images/logo/logo_1.png
  src/images/logo/logo_2.png
  src/images/logo/logo_3.png
  src/images/logo/logo_outline.png
Labels: enhancement

#62 Feature/mainpage
  src/App.js
  src/components/card/Card.js
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#63 Navigation navbar ac
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/logo/full_logo_transparent.png
  src/images/logo/logo_outline.png
  src/images/logo/logo_outline_colour.png
Labels: enhancement

#60 Landingpage login sign handlers hs
  .gitignore
  1.png
  2.png
  3.png
  images/Code Book (1).zip
  public/index.html
  src/App.js
  src/common/index.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/images/homeBookCase.jpeg
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/signupPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/utilities/utilities.js
Labels: enhancement

#64 Feature/navigation
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/logo/full_logo_transparent.png
  src/images/logo/logo_outline.png
  src/images/logo/logo_outline_colour.png
Labels: enhancement

#66 Mainpage css hm
  1.png
  2.png
  3.png
  images/Code Book (1).zip
  package-lock.json
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/icons/book.png
  src/images/icons/heart.png
  src/images/icons/people-arrows.png
  src/images/icons/people-group.png
  src/images/icons/user.png
  src/images/logo/logo_1.png
  src/images/logo/logo_2.png
  src/images/logo/logo_3.png
  src/images/logo/logo_outline.png
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
Labels: enhancement

#70 Mainpage apitodb cs
  src/App.js
  src/common/index.js
  src/components/card/Card.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/navigation/Navbar.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/utilities.js
Labels: enhancement

#71 Signuppage css ac
  package-lock.json
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/images/icons/book.png
  src/images/icons/heart.png
  src/images/icons/people-arrows.png
  src/images/icons/people-group.png
  src/images/icons/user.png
  src/images/logo/full_logo_transparent.png
  src/images/logo/logo_1.png
  src/images/logo/logo_2.png
  src/images/logo/logo_3.png
  src/images/logo/logo_outline_colour.png
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/signupPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
Labels: enhancement

#75 Userprofile delete2 hs
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/pages/mainPage/mainPage.js
Labels: enhancement

#73 delete user functionality completed
  package-lock.json
  package.json
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/pages/mainPage/mainPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/utilities/utilities.js
Labels: enhancement

#76 screen layout corrected for various screen sizes
  src/pages/landingPage/landingPage.css
Labels: enhancement

#74 Feature/mainpage
  src/App.js
  src/common/index.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/navigation/Navbar.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/images/logo/logo_outline_colour.png
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/utilities.js
Labels: enhancement

#79 resolving merge conflict
  src/utilities/utilities.js
Labels: enhancement

#72 Feature/signuppage
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/signupPage.js
Labels: enhancement

#80 Temp sq
  1.png
  2.png
  3.png
  images/Code Book (1).zip
  package-lock.json
  package.json
  src/App.js
  src/common/index.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.css
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/images/icons/book.png
  src/images/icons/heart.png
  src/images/icons/people-arrows.png
  src/images/icons/people-group.png
  src/images/icons/user.png
  src/images/logo/full_logo_transparent.png
  src/images/logo/logo_1.png
  src/images/logo/logo_2.png
  src/images/logo/logo_3.png
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.css
  src/pages/signupPage/signupPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/utilities.js
Labels: enhancement

#77 Feature/landingpage
  src/common/index.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/signupPage/signupPage.js
  src/utilities/utilities.js
Labels: enhancement

#81 updated userprofilepage
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#82 Feature/userprofilepage
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#86 deploy error fixes
  src/components/libraryCard/LibraryCard.js
  src/components/wishlistCard/WishlistCard.js
  src/pages/userprofilePage/userprofilePage.js
Labels: bug

#87 fix deploy css error
  src/components/card/Card.css
  src/components/libraryCard/LibraryCard.css
  src/components/navigation/Navbar.css
  src/components/wishlistCard/WishlistCard.css
  src/pages/landingPage/landingPage.css
  src/pages/wishlistPage/wishlistPage.css
Labels: bug

#91 manual merge user functions
  src/App.js
  src/pages/landingPage/landingPage.js
  src/utilities/userfunctions.js
Labels: enhancement

#93 sq changes
  src/pages/landingPage/landingPage.js
Labels: bug

#94 Dev
  src/App.js
  src/pages/landingPage/landingPage.js
  src/utilities/userfunctions.js
Labels: enhancement

#97 Feature/navigation
  src/App.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
Labels: enhancement

#98 log out button
  src/components/navigation/Navbar.js
  src/images/icons/right-from-bracket.png
Labels: enhancement

#99 Feature/navigation
  src/components/navigation/Navbar.js
  src/images/icons/right-from-bracket.png
Labels: enhancement

#103 Feature/mainpage
  src/components/libraryCard/LibraryCard.js
  src/components/wishlistCard/WishlistCard.js
  src/utilities/utilities.js
Labels: enhancement

#104 Feature/navigation
  public/browser_icon_logo.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
Labels: enhancement

#105 Feature/mainpage useridfix cs
  public/browser_icon_logo.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
Labels: enhancement

#106 Feature/mainpage
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.js
Labels: enhancement

#107 Mainpage css hm
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
Labels: bug, enhancement

#108 Feature/mainpage
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
Labels: bug, enhancement

#110 merge fixes
  src/App.js
  src/components/wishlistCard/WishlistCard.js
Labels: bug

#111 Dev
  public/browser_icon_logo.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/images/icons/right-from-bracket.png
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/utilities.js
Labels: enhancement

#113 token fixes
  src/App.js
  src/components/card/Card.js
  src/pages/landingPage/landingPage.js
  src/pages/signupPage/signupPage.js
  src/utilities/userfunctions.js
  src/utilities/utilities.js
Labels: bug

#118 Mainpage v2 css
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/userfunctions.js
  src/utilities/utilities.js
Labels: enhancement

#120 Userprofilepage deletemodal css sq
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/pages/userprofilePage/userprofilePage.css
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#119 Landingpage cssfix ac
  public/browser_icon_logo.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryCard/LibraryCard.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/bookSearchModal/BookSearchModal.js
  src/components/navigation/Navbar.css
  src/components/navigation/Navbar.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistCard/WishlistCard.js
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/images/icons/right-from-bracket.png
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.css
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/userfunctions.js
  src/utilities/utilities.js
Labels: enhancement

#122 Feature/userprofilepage
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/pages/userprofilePage/userprofilePage.css
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#123 Feature/landingpage
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
Labels: enhancement

#124 final changes css
  src/components/cardContainer/CardContainer.js
  src/components/libraryContainer/LibraryContainer.css
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
Labels: enhancement

#127 Update App.js
  src/App.js
Labels: bug

#128 Landingpage fixbox ac
  src/components/card/Card.css
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/pages/userprofilePage/userprofilePage.css
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
Labels: enhancement

#130 git checkout
  src/pages/signupPage/signupPage.js
  src/utilities/userfunctions.js
  src/utilities/utilities.js
Labels: bug

#131 Feature/community
  src/pages/landingPage/landingPage.js
  src/pages/userprofilePage/userprofilePage.js
  src/utilities/utilities.js
Labels: bug

#132 Landingpage emptyline ac
  src/App.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/signupPage/signupPage.js
  src/utilities/userfunctions.js
  src/utilities/utilities.js
Labels: enhancement

#134 Feature/userprofilepage css sq
  src/App.js
  src/components/card/Card.css
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.js
  src/pages/userprofilePage/userprofilePage.css
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/userfunctions.js
  src/utilities/utilities.js
Labels: enhancement

#136 Feature/userprofilepage
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/pages/userprofilePage/userprofilePage.css
  src/pages/userprofilePage/userprofilePage.js
Labels: enhancement

#137 Dev
  src/App.js
  src/components/card/Card.css
  src/components/card/Card.js
  src/components/cardContainer/CardContainer.css
  src/components/cardContainer/CardContainer.js
  src/components/libraryCard/LibraryCard.css
  src/components/libraryContainer/LibraryContainer.css
  src/components/libraryContainer/LibraryContainer.js
  src/components/modals/deleteusermodal/DeleteUserModal.css
  src/components/modals/deleteusermodal/DeleteUserModal.js
  src/components/wishlistCard/WishlistCard.css
  src/components/wishlistContainer/WishlistContainer.css
  src/components/wishlistContainer/WishlistContainer.js
  src/pages/landingPage/landingPage.css
  src/pages/landingPage/landingPage.js
  src/pages/mainPage/mainPage.js
  src/pages/signupPage/signupPage.js
  src/pages/userprofilePage/userprofilePage.css
  src/pages/userprofilePage/userprofilePage.js
  src/pages/wishlistPage/wishlistPage.css
  src/pages/wishlistPage/wishlistPage.js
  src/utilities/userfunctions.js
  src/utilities/utilities.js
Labels: enhancement

#138 add username to login
  src/utilities/userfunctions.js
Labels: bug

#139 Dev
  src/utilities/userfunctions.js
Labels: bug
